language: android
sudo: required
jdk: oraclejdk8
before_cache: "-rm -f $HOME/.gradle/caches/modules-2/modules-2.lock -rm -fr $HOME/.gradle/caches/*/plugin-resolution/"
cache:
  directories: "-$HOME/.gradle/caches/ -$HOME/.gradle/wrapper/"
env:
  global:
  - ANDROID_API=27
  - ANDROID_BUILD_TOOLS=28.0.3
android:
  components:
  - tools
  - platform-tools
  - build-tools-$ANDROID_BUILD_TOOLS
  - android-$ANDROID_API
  - extra-google-m2repository
  - extra-android-m2repository
script:
  - chmod +x gradlew
  - ./gradlew test
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: setup-travis
